<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <DefineConstants>AVALONIA</DefineConstants>
        <RootNamespace>MapControl.UiTools</RootNamespace>
        <AssemblyTitle>XAML Map Control UI Tools Library for Avalonia UI</AssemblyTitle>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\Shared\*.cs" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaXaml Include="MapLayerInfo.xaml">
            <Generator>MSBuild:Compile</Generator>
        </AvaloniaXaml>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\MapControl\Avalonia\MapControl.Avalonia.csproj" />
    </ItemGroup>
</Project>
